# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-gpu-rdma-vpc
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-gpu-rdma-vpc
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-gpu-rdma-vpc.git
      sourceType: git
    version: 0.0.1
    actuationTool:
      flavor: Terraform
      version: ">= 0.15.0"
    description:
      tagline: This is an auto-generated module.
      detailed: "This module was generated from "
      preDeploy: To deploy this blueprint you must have an active billing account and billing permissions.
    icon: assets/icon.png
    costEstimate:
      description: Blueprint cost details
      url: https://cloud.google.com/products/calculator?id=02fb0c45-cc29-4567-8cc6-f72ac9024add
  content:
    architecture:
      diagramUrl: https://www.link-to-architecture-diagram.com
      description:
        - 1. Architecture description step no. 1
        - 2. Architecture description step no. 2
        - 3. Architecture description step no. N
    documentation:
      - title: Hosting a Static Website
        url: https://cloud.google.com/storage/docs/hosting-static-website
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: Project in which the HPC deployment will be created
        varType: string
        required: true
      - name: network_name
        description: The name of the network to be created (if unsupplied, will default to "{deployment_name}-net")
        varType: string
      - name: region
        description: The default region for Cloud resources
        varType: string
        required: true
      - name: deployment_name
        description: The name of the current deployment
        varType: string
        required: true
      - name: mtu
        description: "The network MTU (default: 8896). Recommended values: 0 (use Compute Engine default), 1460 (default outside HPC environments), 1500 (Internet default), or 8896 (for Jumbo packets). Allowed are all values in the range 1300 to 8896, inclusively."
        varType: number
        defaultValue: 8896
      - name: subnetworks_template
        description: |
          Specifications for the subnetworks that will be created within this VPC.
            
          count       (number, required, number of subnets to create, default is 8)
          name_prefix (string, required, subnet name prefix, default is deployment name)
          ip_range    (string, required, range of IPs for all subnets to share (CIDR format), default is 192.168.0.0/16)
          region      (string, optional, region to deploy subnets to, defaults to vars.region)
        varType: |-
          object({
              count       = number
              name_prefix = string
              ip_range    = string
              region      = optional(string)
            })
        defaultValue:
          count: 8
          ip_range: 192.168.0.0/16
          name_prefix: null
          region: null
      - name: network_routing_mode
        description: The network routing mode (default "REGIONAL")
        varType: string
        defaultValue: REGIONAL
      - name: network_description
        description: An optional description of this resource (changes will trigger resource destroy/create)
        varType: string
        defaultValue: ""
      - name: shared_vpc_host
        description: Makes this project a Shared VPC host if 'true' (default 'false')
        varType: bool
        defaultValue: false
      - name: delete_default_internet_gateway_routes
        description: If set, ensure that all routes within the network specified whose names begin with 'default-route' and with a next hop of 'default-internet-gateway' are deleted
        varType: bool
        defaultValue: false
      - name: enable_internal_traffic
        description: Enable a firewall rule to allow all internal TCP, UDP, and ICMP traffic within the network
        varType: bool
        defaultValue: true
      - name: firewall_rules
        description: List of firewall rules
        varType: any
        defaultValue: []
      - name: firewall_log_config
        description: Firewall log configuration for Toolkit firewall rules (var.enable_iap_ssh_ingress and others)
        varType: string
        defaultValue: DISABLE_LOGGING
      - name: network_profile
        description: |
          A full or partial URL of the network profile to apply to this network.
          This field can be set only at resource creation time. For example, the
          following are valid URLs:
          - https://www.googleapis.com/compute/beta/projects/{projectId}/global/networkProfiles/{network_profile_name}
          - projects/{projectId}/global/networkProfiles/{network_profile_name}}
        varType: string
        required: true
      - name: nic_type
        description: NIC type for use in modules that use the output
        varType: string
        defaultValue: MRDMA
    outputs:
      - name: network_id
        description: ID of the new VPC network
        type: string
      - name: network_name
        description: Name of the new VPC network
        type: string
      - name: network_self_link
        description: Self link of the new VPC network
        type: string
      - name: subnetwork_interfaces
        description: Full list of subnetwork objects belonging to the new VPC network (compatible with vm-instance and Slurm modules)
        type: string
      - name: subnetwork_interfaces_gke
        description: Full list of subnetwork objects belonging to the new VPC network (compatible with gke-node-pool)
        type: string
      - name: subnetwork_name_prefix
        description: Prefix of the RDMA subnetwork names
        type: string
      - name: subnetworks
        description: Full list of subnetwork objects belonging to the new VPC network
        type:
          - list
          - - string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
      - compute.googleapis.com
